
project_id = "mazeeugffraruopozunq"

[functions.setup-admin]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.account-deletion]
verify_jwt = true

[functions.send-verification-pin]
verify_jwt = false

[functions.verify-pin]
verify_jwt = false
