// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mazeeugffraruopozunq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hemVldWdmZnJhcnVvcG96dW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjQ5MzgsImV4cCI6MjA2MDc0MDkzOH0.gZvVFl1Qj1AOFCTt1D073qpl2gpr5CaWv9QmUIZL8zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);